version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - registered_faces:/registered_faces
      - chroma_data:/chroma_storage

volumes:
  registered_faces:
  chroma_data:
