version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./registered_faces:/registered_faces     # face images saved on host
      - ./chroma_storage:/chroma_storage         # chroma DB saved on host

volumes: {}
